// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLJEGXdNbUNGdN9m0f6w-NEkfEBFSN_zE',
    appId: '1:1072073007321:android:c3e4839f7b460a6c219ec8',
    messagingSenderId: '1072073007321',
    projectId: 'whatsdown-747f2',
    storageBucket: 'whatsdown-747f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDamdIDzl6Yxd_L7dR5K10AgVS78DnvTIk',
    appId: '1:1072073007321:ios:e6558ee4c3ebdfa6219ec8',
    messagingSenderId: '1072073007321',
    projectId: 'whatsdown-747f2',
    storageBucket: 'whatsdown-747f2.appspot.com',
    androidClientId: '1072073007321-5udojse9h7s27dl9glfaohr2ii9mnfv7.apps.googleusercontent.com',
    iosClientId: '1072073007321-9241v8a80rdvob4qllaqv1mkrk3kkg27.apps.googleusercontent.com',
    iosBundleId: 'com.whatsdown.in',
  );
}
